### ISSUE TITLE
Dataset state change request / access error / global-seasonal-sentinel-1-interferometric-coherence-and-backscatter-data-set

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/slingshot#571]
## Dataset information

- **Dataset name:** global-seasonal-sentinel-1-interferometric-coherence-and-backscatter-data-set
- **Dataset state:** 
    - [x] "CAR generation complete"
- **Your handle on Filecoin Slack:**  rob

> _We may contact you on Github or on Slack to confirm information_

 ## Change requested
  
- **Correct dataset state:**  
  - [X] "Errored?"

 - **Why is this change being requested?:** 
86 out of 87 .car files are done, but one is errored. Can not upload the datafiles with the provided scripts.

**Comment by justanothersynth** [comment]
@RobQuistNL that final CAR file has a permission issue making it inaccessible, correct?

**Comment by RobQuistNL** [comment]
Yes, there are files that come up with "Permission Denied" on the S3 API. Related: https://github.com/filecoin-project/slingshot/issues/570

**Comment by mithmith** [comment]
While generation process last piece got an error: 'Access Denied'.

**Singularity daemon log:**
2022-08-18T12:19:27.865Z [deal_preparation_worker] warn: Encountered an error when downloading s3://lab41openaudiocorpus/test.txt - AccessDenied: Access Denied - {}
2022-08-18T12:19:27.868Z [deal_preparation_worker] error: Access Denied - {"name":"AccessDenied","$fault":"client","$metadata":{"httpStatusCode":403,"extendedRequestId":"GGiTq9H+D6t362BQtEqaphmuI2bAJAokXOczCqffRuo87yWa9xlJFTRlU+OJqGEl5IbyU7BJ6FU=","attempts":1,"totalRetryDelay":0},"Code":"AccessDenied","RequestId":"CKPXYRJ0R6AGADCT","HostId":"GGiTq9H+D6t362BQtEqaphmuI2bAJAokXOczCqffRuo87yWa9xlJFTRlU+OJqGEl5IbyU7BJ6FU=","stack":"AccessDenied: Access Denied\n    at deserializeAws_restXmlGetObjectCommandError (/home/fil-node/singularity/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6254:24)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/fil-node/singularity/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24\n    at async /home/fil-node/singularity/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20\n    at async StandardRetryStrategy.retry (/home/fil-node/singularity/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)\n    at async /home/fil-node/singularity/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20\n    at async /home/fil-node/singularity/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22\n    at async /home/fil-node/singularity/dist/src/deal-preparation/DealPreparationWorker.js:147:42\n    at async /home/fil-node/singularity/node_modules/p-all/node_modules/p-map/index.js:57:22"}
